/**
 * Italy (IT) Country Configuration
 */

import type { CountryConfig } from "./types";

export const IT_CONFIG: CountryConfig = {
  code: "IT",
  name: "Italy",
  primary_language: "it",
  supported_languages: ["it", "en"],
  default_currency: "EUR",
  vat_rates: [
    { rate: 22, label_key: "standard" },
    { rate: 10, label_key: "reduced" },
    { rate: 4, label_key: "super_reduced" },
    { rate: 0, label_key: "zero" },
  ],
  fiscal_id_fields: [
    {
      field_key: "vat_number",
      required_business: true,
      required_private: false,
      pattern: /^IT\d{11}$/,
      format_hint: "IT + 11 cifre (es. IT01234567890)",
    },
    {
      field_key: "fiscal_code",
      required_business: false,
      required_private: true,
      pattern: /^[A-Z]{6}\d{2}[A-Z]\d{2}[A-Z]\d{3}[A-Z]$/,
      format_hint: "16 caratteri alfanumerici (es. RSSMRA80A01H501U)",
    },
  ],
  einvoicing_ready: false,
  labels: {
    it: {
      document_types: {
        quotation: "Preventivo",
        proforma: "Proforma",
        invoice: "Fattura",
        credit_note: "Nota di Credito",
      },
      document_statuses: {
        draft: "Bozza",
        finalized: "Finalizzato",
        sent: "Inviato",
        paid: "Pagato",
        voided: "Annullato",
      },
      payment_terms: {
        immediate: "Pagamento Immediato",
        NET15: "15 giorni",
        NET30: "30 giorni",
        NET60: "60 giorni",
        NET90: "90 giorni",
        COD: "Contrassegno",
      },
      template: {
        recipient: "Destinatario",
        vat_number: "P.IVA",
        fiscal_code: "C.F.",
        pec_email: "PEC",
        sdi_code: "SDI",
        description: "Descrizione",
        quantity: "Qtà",
        unit_price: "Prezzo Unit.",
        discount: "Sconto",
        vat: "IVA",
        total: "Totale",
        subtotal: "Imponibile",
        notes: "Note",
        date: "Data",
        due_date: "Scadenza",
        payment_terms_label: "Termini",
        document_label: "Documento",
        dear_customer: "Spett.le",
        registered_office: "Sede legale",
        page: "Pagina",
        draft: "BOZZA",
        total_discount: "Sconto totale",
        payment_conditions: "Condizioni di pagamento",
        ico: "",
        dic: "",
        ic_dph: "",
      },
      email: {
        dear_customer: "Gentile",
        attached_document: "In allegato trova il documento",
        pdf_format: "Il documento è allegato in formato PDF.",
        regards: "Cordiali saluti",
      },
      locale: "it-IT",
    },
    en: {
      document_types: {
        quotation: "Quotation",
        proforma: "Proforma Invoice",
        invoice: "Invoice",
        credit_note: "Credit Note",
      },
      document_statuses: {
        draft: "Draft",
        finalized: "Finalized",
        sent: "Sent",
        paid: "Paid",
        voided: "Voided",
      },
      payment_terms: {
        immediate: "Immediate Payment",
        NET15: "Net 15 days",
        NET30: "Net 30 days",
        NET60: "Net 60 days",
        NET90: "Net 90 days",
        COD: "Cash on Delivery",
      },
      template: {
        recipient: "Recipient",
        vat_number: "VAT No.",
        fiscal_code: "Tax Code",
        pec_email: "PEC",
        sdi_code: "SDI",
        description: "Description",
        quantity: "Qty",
        unit_price: "Unit Price",
        discount: "Discount",
        vat: "VAT",
        total: "Total",
        subtotal: "Subtotal",
        notes: "Notes",
        date: "Date",
        due_date: "Due Date",
        payment_terms_label: "Terms",
        document_label: "Document",
        dear_customer: "Dear",
        registered_office: "Registered office",
        page: "Page",
        draft: "DRAFT",
        total_discount: "Total Discount",
        payment_conditions: "Payment Conditions",
        ico: "",
        dic: "",
        ic_dph: "",
      },
      email: {
        dear_customer: "Dear",
        attached_document: "Please find attached the document",
        pdf_format: "The document is attached in PDF format.",
        regards: "Kind regards",
      },
      locale: "en-GB",
    },
  },
};
