/**
 * Slovakia (SK) Country Configuration
 */

import type { CountryConfig } from "./types";

export const SK_CONFIG: CountryConfig = {
  code: "SK",
  name: "Slovakia",
  primary_language: "sk",
  supported_languages: ["sk", "en"],
  default_currency: "EUR",
  vat_rates: [
    { rate: 20, label_key: "standard" },
    { rate: 10, label_key: "reduced" },
  ],
  fiscal_id_fields: [
    {
      field_key: "vat_number",
      required_business: true,
      required_private: false,
      pattern: /^SK\d{10}$/,
      format_hint: "SK + 10 číslic (napr. SK1234567890)",
    },
    {
      field_key: "tax_id",
      required_business: true,
      required_private: false,
      pattern: /^\d{10}$/,
      format_hint: "DIČ: 10 číslic (napr. 1234567890)",
    },
    {
      field_key: "company_id",
      required_business: true,
      required_private: false,
      pattern: /^\d{8}$/,
      format_hint: "IČO: 8 číslic (napr. 12345678)",
    },
  ],
  einvoicing_ready: false,
  labels: {
    sk: {
      document_types: {
        quotation: "Cenová ponuka",
        proforma: "Proforma faktúra",
        invoice: "Faktúra",
        credit_note: "Dobropis",
      },
      document_statuses: {
        draft: "Koncept",
        finalized: "Dokončený",
        sent: "Odoslaný",
        paid: "Zaplatený",
        voided: "Zrušený",
      },
      payment_terms: {
        immediate: "Okamžitá platba",
        NET15: "15 dní",
        NET30: "30 dní",
        NET60: "60 dní",
        NET90: "90 dní",
        COD: "Dobierka",
      },
      template: {
        recipient: "Príjemca",
        vat_number: "IČ DPH",
        fiscal_code: "DIČ",
        pec_email: "",
        sdi_code: "",
        description: "Popis",
        quantity: "Mn.",
        unit_price: "Jedn. cena",
        discount: "Zľava",
        vat: "DPH",
        total: "Celkom",
        subtotal: "Základ dane",
        notes: "Poznámky",
        date: "Dátum",
        due_date: "Splatnosť",
        payment_terms_label: "Platobné podmienky",
        document_label: "Doklad",
        dear_customer: "Vážený",
        registered_office: "Sídlo spoločnosti",
        page: "Strana",
        draft: "KONCEPT",
        total_discount: "Celková zľava",
        payment_conditions: "Platobné podmienky",
        ico: "IČO",
        dic: "DIČ",
        ic_dph: "IČ DPH",
        amount_due: "Suma na úhradu",
      },
      email: {
        dear_customer: "Vážený",
        attached_document: "V prílohe nájdete dokument",
        pdf_format: "Dokument je priložený vo formáte PDF.",
        regards: "S pozdravom",
      },
      locale: "sk-SK",
    },
    en: {
      document_types: {
        quotation: "Quotation",
        proforma: "Proforma Invoice",
        invoice: "Invoice",
        credit_note: "Credit Note",
      },
      document_statuses: {
        draft: "Draft",
        finalized: "Finalized",
        sent: "Sent",
        paid: "Paid",
        voided: "Voided",
      },
      payment_terms: {
        immediate: "Immediate Payment",
        NET15: "Net 15 days",
        NET30: "Net 30 days",
        NET60: "Net 60 days",
        NET90: "Net 90 days",
        COD: "Cash on Delivery",
      },
      template: {
        recipient: "Recipient",
        vat_number: "VAT ID",
        fiscal_code: "Tax ID",
        pec_email: "",
        sdi_code: "",
        description: "Description",
        quantity: "Qty",
        unit_price: "Unit Price",
        discount: "Discount",
        vat: "VAT",
        total: "Total",
        subtotal: "Subtotal",
        notes: "Notes",
        date: "Date",
        due_date: "Due Date",
        payment_terms_label: "Terms",
        document_label: "Document",
        dear_customer: "Dear",
        registered_office: "Registered office",
        page: "Page",
        draft: "DRAFT",
        total_discount: "Total Discount",
        payment_conditions: "Payment Conditions",
        ico: "Company ID",
        dic: "Tax ID",
        ic_dph: "VAT ID",
        amount_due: "Amount Due",
      },
      email: {
        dear_customer: "Dear",
        attached_document: "Please find attached the document",
        pdf_format: "The document is attached in PDF format.",
        regards: "Kind regards",
      },
      locale: "en-GB",
    },
  },
};
